#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#

FROM quay.io/ascend/cann:8.5.1-a3-ubuntu22.04-py3.11

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG MOONCAKE_TAG=v0.3.8.post1
ARG SOC_VERSION="ascend910_9391"
ARG ACTIONS_RESULTS_URL
ARG ACTIONS_RUNTIME_TOKEN
ARG SCCACHE_GHA_ENABLED
ARG MATRIX_ARCH

# Define environments
ENV DEBIAN_FRONTEND=noninteractive
ENV SOC_VERSION=$SOC_VERSION \
    TASK_QUEUE_ENABLE=1 \
    OMP_NUM_THREADS=1

RUN pip config set global.index-url ${PIP_INDEX_URL}

WORKDIR /workspace

COPY ./tools/mooncake_installer.sh /vllm-workspace/vllm-ascend/tools/mooncake_installer.sh

RUN echo "Installing sccache..." \
    && echo "MATRIX_ARCH=${MATRIX_ARCH}" \
    && echo "TARGETPLATFORM=${TARGETPLATFORM}" \
    && case "${MATRIX_ARCH}" in \
      linux/arm64) SCCACHE_ARCH="aarch64" ;; \
      linux/amd64) SCCACHE_ARCH="x86_64" ;; \
      *) echo "Unsupported TARGETPLATFORM for sccache: ${TARGETPLATFORM}" >&2; exit 1 ;; \
    esac \
    && echo "SCCACHE_ARCH=${SCCACHE_ARCH}" \
    && export SCCACHE_DOWNLOAD_URL="${SCCACHE_DOWNLOAD_URL:-https://github.com/mozilla/sccache/releases/download/v0.14.0/sccache-v0.14.0-${SCCACHE_ARCH}-unknown-linux-musl.tar.gz}" \
    && echo "SCCACHE_DOWNLOAD_URL=${SCCACHE_DOWNLOAD_URL}" \
    && echo "Downloading sccache..." \
    && curl -L -o /tmp/sccache.tar.gz ${SCCACHE_DOWNLOAD_URL} \
    && echo "Download completed, extracting..." \
    && tar -xzf /tmp/sccache.tar.gz -C /tmp \
    && echo "Extraction completed, moving to /usr/bin..." \
    && mv /tmp/sccache-v0.14.0-${SCCACHE_ARCH}-unknown-linux-musl/sccache /usr/bin/sccache \
    && chmod +x /usr/bin/sccache \
    && echo "Cleaning up..." \
    && rm -rf /tmp/sccache.tar.gz /tmp/sccache-v0.14.0-${SCCACHE_ARCH}-unknown-linux-musl \
    && export ACTIONS_RESULTS_URL=${ACTIONS_RESULTS_URL} \
    && export ACTIONS_RUNTIME_TOKEN=${ACTIONS_RUNTIME_TOKEN} \
    && export SCCACHE_GHA_ENABLED=${SCCACHE_GHA_ENABLED} \
    && export SCCACHE_KEY_PREFIX=vllm-ascend_ \
    && export SCCACHE_LOG=debug \
    && echo "Starting sccache server..." \
    && sccache --start-server \
    && echo "Showing sccache stats..." \
    && echo "token lenth sccache ${#ACTIONS_RUNTIME_TOKEN}" \
    && sccache --show-stats \
    && echo "sccache installation completed"

# Install Mooncake dependencies
RUN apt-get update -y && \
    apt-get install -y git vim wget net-tools gcc g++ cmake libnuma-dev libjemalloc2 && \
    git clone --depth 1 --branch ${MOONCAKE_TAG} https://github.com/kvcache-ai/Mooncake /vllm-workspace/Mooncake && \
    cp /vllm-workspace/vllm-ascend/tools/mooncake_installer.sh /vllm-workspace/Mooncake/ && \
    cd /vllm-workspace/Mooncake && bash mooncake_installer.sh -y && \
    ARCH=$(uname -m) && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/${ARCH}-linux/devlib:/usr/local/Ascend/ascend-toolkit/latest/${ARCH}-linux/lib64:$LD_LIBRARY_PATH && \
    mkdir -p build && cd build && cmake .. -DUSE_ASCEND_DIRECT=ON -DENABLE_SCCACHE=ON && \
    make -j$(nproc) && make install && \
    sccache --show-stats && \
    rm -fr /vllm-workspace/Mooncake/build && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*

# Install vLLM
ARG VLLM_REPO=https://github.com/vllm-project/vllm.git
ARG VLLM_TAG=v0.18.0
RUN git clone --depth 1 $VLLM_REPO --branch $VLLM_TAG /vllm-workspace/vllm
# In x86, triton will be installed by vllm. But in Ascend, triton doesn't work correctly. we need to uninstall it.
RUN VLLM_TARGET_DEVICE="empty" python3 -m pip install -v -e /vllm-workspace/vllm/[audio] --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton && \
    sccache --stop-server && \
    python3 -m pip cache purge

RUN echo "export LD_PRELOAD=/usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2:$LD_PRELOAD" >> ~/.bashrc
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" >> ~/.bashrc

CMD ["/bin/bash"]